### ISSUE TITLE
Mecanismo de favoritar

### ISSUE THREAD

**Issue by rviannaoliveira** [CodandoTV/StreamPlayerApp#20]
O projeto netflix (product real), tem um ícone chamado minha lista (quando o movie não está favoritado):
![image](https://github.com/CodandoTV/StreamPlayerApp/assets/9204234/3236ab54-e77c-4a72-a589-9af823082845)

Ao favoritar, nós temos a mudança do ícone para:

![image](https://github.com/CodandoTV/StreamPlayerApp/assets/9204234/f374650f-d363-4e87-a321-d46aa62a7051)

Além disso, uma toast message é exibida a cada ação.

---

## Tech details
- Utilizar `data store` pra persistir o movie na lista de favoritos.

**Comment by rodrigoliveirac** [comment]
Posso contribuir com essa issue?
