### ISSUE TITLE
Montar wiki explicando o porque das tecnologias

### ISSUE THREAD

**Issue by rviannaoliveira** [CodandoTV/StreamPlayerApp#4]
trabalhar no versionamento da wiki

**Comment by gabrielbmoro** [comment]
Acho que essa issue poderia ser quebrada em várias issues, uma pra cada tecnologia, o que acham?
@carlosvaccari / @rviannaoliveira

**Comment by carlosvaccari** [comment]
Boa! Acho q faz mais sentido. Isso será uma construção constante.

**Comment by gabrielbmoro** [comment]
@rviannaoliveira e @carlosvaccari , eu adicionei as seguintes páginas:

- https://github.com/CodandoTV/StreamPlayerApp/wiki/Quais-tecnologias-o-projeto-utiliza%3F;
- https://github.com/CodandoTV/StreamPlayerApp/wiki/Porque-tantos-m%C3%B3dulos-no-projeto%3F.

Aguardo revisão para fecharmos essa issue 🤗
