### ISSUE TITLE
a integração do scroll na tela da lista

### ISSUE THREAD

**Issue by rviannaoliveira** [CodandoTV/StreamPlayerApp#44]

**Comment by gabrielbmoro** [comment]
@carlosvaccari , uma dúvida, essa issue a gente já fez né? 🤔

**Comment by carlosvaccari** [comment]
Acho q criamos esse pra fazer a animação da topbar (n lembro agora). Ainda tinha um bug, mas parece q seu PR já corrigiu isso. Depois deixa aqui qual foi o fix e vamos fechar esse issue, pode ser?
