### ISSUE TITLE
Remover API token hard coded para usar alguma variável de ambiente

### ISSUE THREAD

**Issue by gabrielbmoro** [CodandoTV/StreamPlayerApp#56]
Dentro do nosso `NetworkModule` estamos utilizando um token hardcoded. O ideal seria a gente pegar esse token de variável de ambiente.

### Wiki Page - Como fazer executar o projeto
- [ ] Descrever em uma sessão de como criar uma conta na MovieDB pra ter acesso ao token
- [ ] Especificar como o token deve ser registrado localmente no projeto

### Código
- [ ] Definir uma forma de puxar a variável de ambiente e expor ela no próprio gradle como build config variable;
- [ ] Remover o token hardcoded e passar a utilizar o valor da variável que contém o token.

Logo após essa implementação, a gente precisa avisar no discord pra galera criar um conta e usar o seu próprio token pra não quebrar o projeto

**Comment by cassioferrazzo** [comment]
Não seria mais interessante criar tópicos na wiki e referenciar isso no readme? Pq se for adicionar imagens e comandos de terminal vai ficar muito extenso pra estar no readme.

**Comment by gabrielbmoro** [comment]
> Não seria mais interessante criar tópicos na wiki e referenciar isso no readme? Pq se for adicionar imagens e comandos de terminal vai ficar muito extenso pra estar no readme.

Perfeito @cassioferrazzo 

É verdade, vai ficar bacana mover isso pra wiki!

**Comment by cassioferrazzo** [comment]
@gabrielbmoro O ajuste no código está feito e aí está a PR para review.
Sobre a wiki acredito que não tenha permissão para editar, mas estou fazendo as docs aqui e depois que resolvermos essa questão já subo os tópicos.
